#! /bin/bash

source="/opt/amagill/src/hammerspoon/hammerspoon"

for folder in [a-z]* ; do
    if [ -d $folder ]; then
#         if [ $folder != "_luathreadcoreadditions" ]; then
            echo "-- $folder --"
            cd $folder
            for diffFile in *.diff ; do
                file=${diffFile%.diff}
                originalFile="${source}/extensions/${folder//\.//}/${file}"
                diff $file $originalFile > ${file}.tmp
                diff $diffFile ${file}.tmp &> /dev/null || echo "   ${file} file differences have changed"
                rm ${file}.tmp
            done
            cd ..
#         fi
    fi
done
